# Name of the GitHub Action
name: Compile LaTeX Resume

# This action runs on pushes to the main branch...
on:
  push:
    branches: [ "main" ]
    # ...but ONLY if the resume.tex file was changed.
    # This saves you from running it unnecessarily.
    paths:
      - 'resume.tex'

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository so the workflow can access your files.
      - name: Set up Git repository
        uses: actions/checkout@v4

      # 2. Compiles the resume.tex file into resume.pdf.
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      # 3. Commits the newly generated PDF file back to your repository.
      # This is the key step that was missing.
      - name: Commit resulting PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          # Only commit and push if the PDF file has actually changed
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Auto-compile resume.pdf"
            git push
          fi