# Name of the GitHub Action
name: Compile LaTeX Resume

on:
  push:
    branches: [ "main" ]
    paths:
      - 'resume.tex'

# Permissions needed to commit the new PDF back to the repository
permissions:
  contents: write

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository
      - name: Set up Git repository
        uses: actions/checkout@v4

      # 2. Compiles the resume.tex file
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      # 3. Commits the new PDF
      - name: Commit resulting PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          # Only commit and push if the PDF file has actually changed
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Auto-compile resume.pdf"
            git push
          fi