name: Build LaTeX Resume

on:
  push:
    branches:
      - main

# ADD THIS PART to give the action permission to write the PDF back
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f *.pdf
          git commit -m "Generate resume PDF" || echo "No changes to commit"
          git push || echo "No changes to push"