name: Build and Deploy LaTeX Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write  # To push the generated PDF back to the repo
  pages: write     # To deploy to GitHub Pages
  id-token: write  # Required for trusted deployment

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          
      - name: Commit PDF to repo # This step keeps the PDF in your main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f *.pdf
          git commit -m "Generate resume PDF" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3 # <-- This is the NEW version
        with:
         path: .

  deploy_pages:
    needs: build_latex # This job runs only after the PDF is built
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1